version: '3.8'

services:
  frontend:
    build:
      context: ./explorahub
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./explorahubflask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
